nelmio_cors:
    defaults:
        allow_credentials: true  # Allow sending cookies (JWT)
        allow_origin: ['http://localhost:4200', 'http://127.0.0.1:8000']  # Frontend URLs
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['POST', 'GET', 'DELETE', 'PUT', 'OPTIONS']
        expose_headers: ['Authorization']
        max_age: 3600  # Cache preflight requests for 1 hour

    paths:
        '^/api/':  # Apply these rules to all API routes
            allow_origin: ['http://localhost:4200']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'GET', 'DELETE', 'PUT', 'OPTIONS']
            max_age: 3600
