security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/ 
            security: false

        main:
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker  # ✅ Add this line
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                csrf_token_id: authenticate
                default_target_path: app_film_index
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 604800
                path: /
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            entry_point: App\Security\LoginFormAuthenticator

        api:
            pattern: ^/api/
            provider: app_user_provider
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/api/comments, roles: ROLE_ADMIN }
