controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_forgot_password_request:
    path: /reset-password
    controller: App\Controller\ResetPasswordController::request

app_reset_password:
    path: /reset-password/{token}
    controller: App\Controller\ResetPasswordController::reset
